# Generated by Django 2.1 on 2019-02-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticket_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='phone',
        ),
    ]
