# Generated by Django 2.1 on 2019-02-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_remove_ticket_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
